### PR TITLE
TraceReader and TraceData

### PR DESCRIPTION
**Pull request by kajdreef**
I modified the TraceData to be a singleton so we can access the data from anywhere in the program while providing some encapsulation. Currently, this works fine with what I'm working on now.
If someone (@VijayKrishna) has any suggestions for further improvements let me know :)

### CODE REVIEW

**Comment by jycamus90** [comment]
Question) Does this change work with reading multiple trace files? The reason that I moved _insnTable_ and _methodDeclTable_ to a separate class file and made them **public static** was to maintain one static _insnTable_ and _methodDeclTable_, while reading multiple trace files. Now, Blinky creates a separate trace file per test method (case). Due to this change, when Cerebro reads multiple trace files through TraceReader, TraceReader needs to maintain global Map that contains all the information about the events that TraceReader already has processed. I think if we make _insnTable_ and _methodDeclTable_ private, Cerebro will crash when reading the trace files.

**Comment by VijayKrishna** [comment]
@jycamus90 a TraceReader instance has a reference to a TraceData object that gets pointed to a singleton (see `TraceData. getInstance()`). So in effect, a single TraceData object persists across all TraceReader objects.

**Comment by VijayKrishna** [comment]
@kajdreef, @jycamus90 - for the record, this change does not seem to break `mvn test install package`

**Comment by jycamus90** [comment]
Yep all works.

**Pull request merged**
